config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users do
    member do
      get :followings
      get :followers
      get :refusals
      get :refusers
      get :likes
      get :joy
      get :angry
      get :sad
      get :happy
    end
  end
  
  resources :posts, only: [:create, :destroy, :new, :show] do
    resources :comments, only: [:create, :destroy, :show, :index]
    member do
      get :joy
      get :angry
      get :sad
      get :happy
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :rejects, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :notifications, only: :index
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :posts, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :user
  
  has_many :rejects, dependent: :destroy
  has_many :refusals, through: :rejects, source: :reject
  has_many :reverses_of_reject, class_name: 'Reject', foreign_key: 'reject_id'
  has_many :refusers, through: :reverses_of_reject, source: :user
  
  has_many :favorites, dependent: :destroy
  has_many :likes, through: :favorites, source: :post, dependent: :destroy
  
  has_many :comments, dependent: :destroy
  
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def refuse(other_user)
    unless self == other_user
      self.rejects.find_or_create_by(reject_id: other_user.id)
    end
  end
  
  def unrefuse(other_user)
    reject = self.rejects.find_by(reject_id: other_user.id)
    reject.destroy if reject
  end
  
  def refusing?(other_user)
    self.refusals.include?(other_user)
  end
  
  def favorite(postFavorite)
    self.favorites.find_or_create_by(post_id: postFavorite.id)
  end
  
  def unfavorite(postFavorite)
    favorite = self.favorites.find_by(post_id: postFavorite.id)
    favorite.destroy if favorite
  end
  
  def favoritePost?(postFavorite)
    self.likes.include?(postFavorite)
  end
  
  def feed_posts
    Post.where.not(user_id: self.refusal_ids)
  end
  
  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
  
  mount_uploader :image, ImageUploader
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  
  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.all.order(id: "DESC")
    counts(@user)
    emotion
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      flash[:success] = 'プロフィールを更新しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'プロフィールを更新できませんでした。'
      render :edit
    end
  end

  def destroy
  end
  
  def joy
    @user = User.find(params[:id])
    @posts = @user.posts.where(joy: true).order(id: "DESC")
    emotion
  end
  
  def angry
    @user = User.find(params[:id])
    @posts = @user.posts.where(angry: true).order(id: "DESC")
    emotion
  end
  
  def sad
    @user = User.find(params[:id])
    @posts = @user.posts.where(sad: true).order(id: "DESC")
    emotion
  end
  
  def happy
    @user = User.find(params[:id])
    @posts = @user.posts.where(happy: true).order(id: "DESC")
    emotion
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :profile, :image)
  end
  
  def emotion
    @joy = @user.posts.where(joy: true).count
    @angry = @user.posts.where(angry: true).count
    @sad = @user.posts.where(sad: true).count
    @happy = @user.posts.where(happy: true).count
    @chart = [['よろこび', @joy], ['いかり', @angry], ['かなしい', @sad], ['うれしい', @happy]]
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/users/_profile.html.erb
<div class="left-bar d-none d-sm-block col-sm-6 col-lg-3 profile">
  
  <% if user.image.file.nil? %>
    <%= image_tag 'user-pict.png', size: "100x100", class: "profile-image" %>
  <% else %>
    <img src=<%= user.image %> width="100" height="100" class="profile-image">
  <% end %>
  
  <h3 class="mt-2 profile-username"><%= user.name %></h3>
  <p><%= user.profile %></p>
  <% if current_user.id == user.id %>
    <%= link_to '編集する', edit_user_path, class: "btn btn-primary mt-2" %>
    <%= link_to 'ログアウト', logout_path, method: :delete, class: "btn btn-primary mt-2" %>
  <% end %>
  <div class="other-user">
    <%= render 'rejects/reject_button', user: user %>
  </div>
</div>
<div class="profile-xs col-6 d-block d-sm-none mb-4">
  <% if user.image.file.nil? %>
    <%= image_tag 'user-pict.png', size: "100x100", class: "profile-image" %>
  <% else %>
    <img src=<%= user.image %> width="100" height="100" class="profile-image">
  <% end %>
  <h5 class="mt-2 profile-username"><%= user.name %></h5>
  <p><%= simple_format(user.profile) %></p>
  <% if current_user.id == user.id %>
    <%= link_to '編集する', edit_user_path, class: "btn btn-primary mt-2" %>
    <%= link_to 'ログアウト', logout_path, method: :delete, class: "btn btn-primary mt-2" %>
  <% end %>
  <%= render 'rejects/reject_button', user: user %>
</div>

<div class="right-bar  col-md-6 d-none d-md-block d-lg-none">
  <%= column_chart @chart, width: '250px',height: '250px' %>
</div>
<div class="right-bar col-sm-6 d-none d-sm-block d-md-none">
  <%= column_chart @chart, width: '250px',height: '250px' %>
</div>
<div class="charts-xs d-block d-sm-none">
  <%= column_chart @chart, width: '235px',height: '235px' %>
</div>

app/views/users/_user.html.erb
<div class="container">  
  <div class="row">
    <%= render 'users/profile', user: @user %>
    
    <div class="center-field col-lg-7">
      <ul class="nav nav-tabs nav-justified mb-3">
        <li class="nav-item"><a href="<%= user_path(user) %>" class="nav-link <%= 'active' if current_page?(user_path(user)) %>">投稿  <span class="badge badge-secondary"><%= @count_posts %></span></a></li>
        <li class="nav-item"><a href="<%= joy_user_path(user) %>" class="nav-link <%= 'active' if current_page?(joy_user_path(user)) %>">よろこび  <span class="badge badge-secondary"></span></a></li>
        <li class="nav-item"><a href="<%= angry_user_path(user) %>" class="nav-link <%= 'active' if current_page?(angry_user_path(user)) %>">いかり  <span class="badge badge-secondary"></span></a></li>
        <li class="nav-item"><a href="<%= sad_user_path(user) %>" class="nav-link <%= 'active' if current_page?(sad_user_path(user)) %>">かなしい  <span class="badge badge-secondary"></span></a></li>
        <li class="nav-item"><a href="<%= happy_user_path(user) %>" class="nav-link <%= 'active' if current_page?(happy_user_path(user)) %>">たのしい  <span class="badge badge-secondary"></span></a></li>
      </ul>
      <% posts.each do |post| %>
      
        <div class="card">
          <div class="card-body">
            <div class="post">
              <div class="post-left">
                <%= link_to user_path(post.user) do %>
                  <img src=<%= post.user.image %> width="50" height="50" class="timeline-profile-image">
                <% end %>
              </div>
              
              <div class="post-right ml-2">
                <p class="username"><%= link_to post.user.name, user_path(post.user), class: "link", :style=>"color:black;" %></p>
                <p class="content"><%= link_to simple_format(post.content), post_path(post), :style=>"color:black;", class: "link" %></p>
                <p class="created_at"><%= post.created_at.strftime("%Y-%m-%d %H:%M") %></p>
              </div>
            </div>
            <div class="emotion ml-5">
              <% if post.joy? %>
                <%= image_tag 'joy.png', size: "25x25", class: "mr-5" %>
              <% else %>
                <%= image_tag 'TrMNZcqite9ERPy1574251959_1574252009.png', size: "25x25", class: "mr-5" %>
              <% end %>
              
              <% if post.angry? %>
                <%= image_tag 'angry.png', size: "25x25", class: "mr-5" %>
              <% else %>
                <%= image_tag 'b69imeB0ifKLEYj1574252373_1574252384.png', size: "25x25", class: "mr-5" %>
              <% end %>
              
              <% if post.sad? %>
                <%= image_tag 'sad.png', size: "25x25", class: "mr-5" %>
              <% else %>
                <%= image_tag '97UGwqcW1pYLGvY1574252540_1574252550.png', size: "25x25", class: "mr-5" %>
              <% end %>
              
              <% if post.happy? %>
                <%= image_tag 'happy.png', size: "25x25", class: "mr-5" %>
              <% else %>
                <%= image_tag 'xDwa9RHTN6U7VXT1574252642_1574252647.png', size: "25x25", class: "mr-5" %>
              <% end %>
              
              
              <!-- <%= link_to "投稿を削除する", post, method: :delete, data: { confirm: "本当に削除してもよいですか?" }, class: 'btn btn-danger btn-sm' %> -->
            </div>
          </div>
        </div>
      
    <% end %>
    </div>
    <div class="right-bar col-lg-2">
      <%= column_chart @chart, width: '250px',height: '250px' %>
    </div>
  </div>  
</div>

app/views/users/angry.html.erb
<div class="container">  
  <div class="row">
    <%= render 'users/profile', user: @user %>
    
    
    <div class="center-field col-lg-7">
      <ul class="nav nav-tabs nav-justified mb-3">
        <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">投稿  <span class="badge badge-secondary"><%= @count_posts %></span></a></li>
        <li class="nav-item"><a href="<%= joy_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(joy_user_path(@user)) %>">よろこび  <span class="badge badge-secondary"></span></a></li>
        <li class="nav-item"><a href="<%= angry_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(angry_user_path(@user)) %>">いかり  <span class="badge badge-secondary"></span></a></li>
        <li class="nav-item"><a href="<%= sad_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(sad_user_path(@user)) %>">かなしい  <span class="badge badge-secondary"></span></a></li>
        <li class="nav-item"><a href="<%= happy_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(happy_user_path(@user)) %>">たのしい  <span class="badge badge-secondary"></span></a></li>
      </ul>
      <% @posts.each do |post| %>
      
        <div class="card">
          <div class="card-body">
            <div class="post">
              <div class="post-left">
                <%= link_to user_path(post.user) do %>
                  <% if post.user.image.file.nil? %>
                    <%= image_tag 'user-pict.png', size: "50x50", class: "timeline-profile-image" %>
                  <% else %>
                    <img src=<%= post.user.image %> width="50" height="50" class="timeline-profile-image">
                  <% end %>
                <% end %>
              </div>
              
              <div class="post-right ml-2">
                <p class="username"><%= link_to post.user.name, user_path(post.user), class: "link", :style=>"color:black;" %></p>
                <p class="content"><%= link_to simple_format(post.content), post_path(post), :style=>"color:black;", class: "link" %></p>
                <p class="created_at"><%= post.created_at.strftime("%Y-%m-%d %H:%M") %></p>
              </div>
            </div>
            <div class="emotion ml-5">
              <% if post.joy? %>
                <%= image_tag 'joy.png', size: "25x25", class: "mr-5" %>
              <% else %>
                <%= image_tag 'TrMNZcqite9ERPy1574251959_1574252009.png', size: "25x25", class: "mr-5" %>
              <% end %>
              
              <% if post.angry? %>
                <%= image_tag 'angry.png', size: "25x25", class: "mr-5" %>
              <% else %>
                <%= image_tag 'b69imeB0ifKLEYj1574252373_1574252384.png', size: "25x25", class: "mr-5" %>
              <% end %>
              
              <% if post.sad? %>
                <%= image_tag 'sad.png', size: "25x25", class: "mr-5" %>
              <% else %>
                <%= image_tag '97UGwqcW1pYLGvY1574252540_1574252550.png', size: "25x25", class: "mr-5" %>
              <% end %>
              
              <% if post.happy? %>
                <%= image_tag 'happy.png', size: "25x25", class: "mr-5" %>
              <% else %>
                <%= image_tag 'xDwa9RHTN6U7VXT1574252642_1574252647.png', size: "25x25", class: "mr-5" %>
              <% end %>
              
              
              <!-- <%= link_to "投稿を削除する", post, method: :delete, data: { confirm: "本当に削除してもよいですか?" }, class: 'btn btn-danger btn-sm' %> -->
            </div>
          </div>
        </div>
      
    <% end %>
    </div>
    <div class="right-bar d-none d-lg-block col-lg-2">
      <%= column_chart @chart, width: '250px',height: '250px' %>
    </div>
  </div>  
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-sm-6 offset-sm-3 pt-5">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'ユーザーネーム' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワードの確認' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :profile, 'プロフィール' %>
        <%= f.text_area :profile, size: "20x10", class: 'form-control' %>
      </div>
      
      <div class="field">
        <p class="image-label"><%= f.label :image, 'プロフィール画像' %></p>
        <%= f.file_field :image %>
      </div>

      <%= f.submit '登録する', class: 'btn btn-primary btn-lg mx-auto d-block active mb-5 mt-3' %>
    <% end %>
  </div>
</div>

app/views/users/happy.html.erb
<div class="container">  
  <div class="row">
    <%= render 'users/profile', user: @user %>
    
    
    <div class="center-field col-lg-7">
      <ul class="nav nav-tabs nav-justified mb-3">
        <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">投稿  <span class="badge badge-secondary"><%= @count_posts %></span></a></li>
        <li class="nav-item"><a href="<%= joy_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(joy_user_path(@user)) %>">よろこび  <span class="badge badge-secondary"></span></a></li>
        <li class="nav-item"><a href="<%= angry_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(angry_user_path(@user)) %>">いかり  <span class="badge badge-secondary"></span></a></li>
        <li class="nav-item"><a href="<%= sad_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(sad_user_path(@user)) %>">かなしい  <span class="badge badge-secondary"></span></a></li>
        <li class="nav-item"><a href="<%= happy_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(happy_user_path(@user)) %>">たのしい  <span class="badge badge-secondary"></span></a></li>
      </ul>
      <% @posts.each do |post| %>
      
        <div class="card">
          <div class="card-body">
            <div class="post">
              <div class="post-left">
                <%= link_to user_path(post.user) do %>
                  <% if post.user.image.file.nil? %>
                    <%= image_tag 'user-pict.png', size: "50x50", class: "timeline-profile-image" %>
                  <% else %>
                    <img src=<%= post.user.image %> width="50" height="50" class="timeline-profile-image">
                  <% end %>
                <% end %>
              </div>
              
              <div class="post-right ml-2">
                <p class="username"><%= link_to post.user.name, user_path(post.user), class: "link", :style=>"color:black;" %></p>
                <p class="content"><%= link_to simple_format(post.content), post_path(post), :style=>"color:black;", class: "link" %></p>
                <p class="created_at"><%= post.created_at.strftime("%Y-%m-%d %H:%M") %></p>
              </div>
            </div>
            <div class="emotion ml-5">
              <% if post.joy? %>
                <%= image_tag 'joy.png', size: "25x25", class: "mr-5" %>
              <% else %>
                <%= image_tag 'TrMNZcqite9ERPy1574251959_1574252009.png', size: "25x25", class: "mr-5" %>
              <% end %>
              
              <% if post.angry? %>
                <%= image_tag 'angry.png', size: "25x25", class: "mr-5" %>
              <% else %>
                <%= image_tag 'b69imeB0ifKLEYj1574252373_1574252384.png', size: "25x25", class: "mr-5" %>
              <% end %>
              
              <% if post.sad? %>
                <%= image_tag 'sad.png', size: "25x25", class: "mr-5" %>
              <% else %>
                <%= image_tag '97UGwqcW1pYLGvY1574252540_1574252550.png', size: "25x25", class: "mr-5" %>
              <% end %>
              
              <% if post.happy? %>
                <%= image_tag 'happy.png', size: "25x25", class: "mr-5" %>
              <% else %>
                <%= image_tag 'xDwa9RHTN6U7VXT1574252642_1574252647.png', size: "25x25", class: "mr-5" %>
              <% end %>
              
              
              <!-- <%= link_to "投稿を削除する", post, method: :delete, data: { confirm: "本当に削除してもよいですか?" }, class: 'btn btn-danger btn-sm' %> -->
            </div>
          </div>
        </div>
      
    <% end %>
    </div>
    <div class="right-bar d-none d-lg-block col-lg-2">
      <%= column_chart @chart, width: '250px',height: '250px' %>
    </div>
  </div>  
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/joy.html.erb
<div class="container">  
  <div class="row">
    <%= render 'users/profile', user: @user %>
    
    
    <div class="center-field col-lg-7">
      <ul class="nav nav-tabs nav-justified mb-3">
        <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">投稿  <span class="badge badge-secondary"><%= @count_posts %></span></a></li>
        <li class="nav-item"><a href="<%= joy_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(joy_user_path(@user)) %>">よろこび  <span class="badge badge-secondary"></span></a></li>
        <li class="nav-item"><a href="<%= angry_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(angry_user_path(@user)) %>">いかり  <span class="badge badge-secondary"></span></a></li>
        <li class="nav-item"><a href="<%= sad_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(sad_user_path(@user)) %>">かなしい  <span class="badge badge-secondary"></span></a></li>
        <li class="nav-item"><a href="<%= happy_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(happy_user_path(@user)) %>">たのしい  <span class="badge badge-secondary"></span></a></li>
      </ul>
      <% @posts.each do |post| %>
      
        <div class="card">
          <div class="card-body">
            <div class="post">
              <div class="post-left">
                <%= link_to user_path(post.user) do %>
                  <% if post.user.image.file.nil? %>
                    <%= image_tag 'user-pict.png', size: "50x50", class: "timeline-profile-image" %>
                  <% else %>
                    <img src=<%= post.user.image %> width="50" height="50" class="timeline-profile-image">
                  <% end %>
                <% end %>
              </div>
              
              <div class="post-right ml-2">
                <p class="username"><%= link_to post.user.name, user_path(post.user), class: "link", :style=>"color:black;" %></p>
                <p class="content"><%= link_to simple_format(post.content), post_path(post), :style=>"color:black;", class: "link" %></p>
                <p class="created_at"><%= post.created_at.strftime("%Y-%m-%d %H:%M") %></p>
              </div>
            </div>
            <div class="emotion ml-5">
              <% if post.joy? %>
                <%= image_tag 'joy.png', size: "25x25", class: "mr-5" %>
              <% else %>
                <%= image_tag 'TrMNZcqite9ERPy1574251959_1574252009.png', size: "25x25", class: "mr-5" %>
              <% end %>
              
              <% if post.angry? %>
                <%= image_tag 'angry.png', size: "25x25", class: "mr-5" %>
              <% else %>
                <%= image_tag 'b69imeB0ifKLEYj1574252373_1574252384.png', size: "25x25", class: "mr-5" %>
              <% end %>
              
              <% if post.sad? %>
                <%= image_tag 'sad.png', size: "25x25", class: "mr-5" %>
              <% else %>
                <%= image_tag '97UGwqcW1pYLGvY1574252540_1574252550.png', size: "25x25", class: "mr-5" %>
              <% end %>
              
              <% if post.happy? %>
                <%= image_tag 'happy.png', size: "25x25", class: "mr-5" %>
              <% else %>
                <%= image_tag 'xDwa9RHTN6U7VXT1574252642_1574252647.png', size: "25x25", class: "mr-5" %>
              <% end %>
              
              
              <!-- <%= link_to "投稿を削除する", post, method: :delete, data: { confirm: "本当に削除してもよいですか?" }, class: 'btn btn-danger btn-sm' %> -->
            </div>
          </div>
        </div>
      
    <% end %>
    </div>
    <div class="right-bar d-none d-lg-block col-lg-2">
      <%= column_chart @chart, width: '250px',height: '250px' %>
    </div>
  </div>  
</div>

app/views/users/new.html.erb
<%= render 'forms', user: @user %>

app/views/users/sad.html.erb
<div class="container">  
  <div class="row">
    <%= render 'users/profile', user: @user %>
    
    
    <div class="center-field col-lg-7">
      <ul class="nav nav-tabs nav-justified mb-3">
        <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">投稿  <span class="badge badge-secondary"><%= @count_posts %></span></a></li>
        <li class="nav-item"><a href="<%= joy_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(joy_user_path(@user)) %>">よろこび  <span class="badge badge-secondary"></span></a></li>
        <li class="nav-item"><a href="<%= angry_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(angry_user_path(@user)) %>">いかり  <span class="badge badge-secondary"></span></a></li>
        <li class="nav-item"><a href="<%= sad_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(sad_user_path(@user)) %>">かなしい  <span class="badge badge-secondary"></span></a></li>
        <li class="nav-item"><a href="<%= happy_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(happy_user_path(@user)) %>">たのしい  <span class="badge badge-secondary"></span></a></li>
      </ul>
      <% @posts.each do |post| %>
      
        <div class="card">
          <div class="card-body">
            <div class="post">
              <div class="post-left">
                <%= link_to user_path(post.user) do %>
                  <% if post.user.image.file.nil? %>
                    <%= image_tag 'user-pict.png', size: "50x50", class: "timeline-profile-image" %>
                  <% else %>
                    <img src=<%= post.user.image %> width="50" height="50" class="timeline-profile-image">
                  <% end %>
                <% end %>
              </div>
              
              <div class="post-right ml-2">
                <p class="username"><%= link_to post.user.name, user_path(post.user), class: "link", :style=>"color:black;" %></p>
                <p class="content"><%= link_to simple_format(post.content), post_path(post), :style=>"color:black;", class: "link" %></p>
                <p class="created_at"><%= post.created_at.strftime("%Y-%m-%d %H:%M") %></p>
              </div>
            </div>
            <div class="emotion ml-5">
              <% if post.joy? %>
                <%= image_tag 'joy.png', size: "25x25", class: "mr-5" %>
              <% else %>
                <%= image_tag 'TrMNZcqite9ERPy1574251959_1574252009.png', size: "25x25", class: "mr-5" %>
              <% end %>
              
              <% if post.angry? %>
                <%= image_tag 'angry.png', size: "25x25", class: "mr-5" %>
              <% else %>
                <%= image_tag 'b69imeB0ifKLEYj1574252373_1574252384.png', size: "25x25", class: "mr-5" %>
              <% end %>
              
              <% if post.sad? %>
                <%= image_tag 'sad.png', size: "25x25", class: "mr-5" %>
              <% else %>
                <%= image_tag '97UGwqcW1pYLGvY1574252540_1574252550.png', size: "25x25", class: "mr-5" %>
              <% end %>
              
              <% if post.happy? %>
                <%= image_tag 'happy.png', size: "25x25", class: "mr-5" %>
              <% else %>
                <%= image_tag 'xDwa9RHTN6U7VXT1574252642_1574252647.png', size: "25x25", class: "mr-5" %>
              <% end %>
              
              
              <!-- <%= link_to "投稿を削除する", post, method: :delete, data: { confirm: "本当に削除してもよいですか?" }, class: 'btn btn-danger btn-sm' %> -->
            </div>
          </div>
        </div>
      
    <% end %>
    </div>
    <div class="right-bar d-none d-lg-block col-lg-2">
      <%= column_chart @chart, width: '250px',height: '250px' %>
    </div>
  </div>  
</div>