config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users do
    member do
      get :followings
      get :followers
      get :refusals
      get :refusers
      get :likes
      get :joy
      get :angry
      get :sad
      get :happy
    end
  end
  
  resources :posts, only: [:create, :destroy, :new, :show] do
    resources :comments, only: [:create, :destroy, :show, :index]
    member do
      get :joy
      get :angry
      get :sad
      get :happy
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :rejects, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :notifications, only: :index
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  
  def index
    if logged_in?
      @posts = current_user.feed_posts.order(id: :desc)
    end
  end
end

app/views/toppages/_before_login.html.erb
<div class="row">
  <div class="center jumbotron background-image col-12 mb-5">
    <div class="text-center">
      <h1>キドアイラク</h1>
      <p>ネット世界に「表情」をつけるSNS</p>
      <%= link_to "新規登録", new_user_path, class: "btn-gradient-radius" %>
      <%= link_to "ログイン", login_path, class: "btn-gradient-radius" %>
    </div>
  </div>
  <div class="paragraph mb-5">
    <h2 class="col-md-6 offset-md-3"><i class="fas fa-eye"></i> 人の感情が一目でわかる</h2>
    <p class="col-md-6 offset-md-3">キドアイラクでは文章を投稿する際に、自分の気持ちを喜怒哀楽の4つの感情で表現してもらいます。文章を投稿するたびに自分の感情と向き合うことで、常に自己分析する習慣をつけることができます。また、SNS特有の少ない文字数では感じ取れない機微な感情を、感情マークを見ることで感じ取ることが可能になりました。</p>
    <img class="col-md-6 paragraph-image" src="timeline.png">
  </div>
  <div class="paragraph mb-5">
    <h2 class="col-md-6 offset-md-3"><i class="fas fa-chart-bar"></i> 自分の感情を分析できる</h2>
    <p class="col-md-6 offset-md-3">マイページでは、いつも自分がどんな気持ちでいるかを把握できる「感情グラフ」を見ることができます。「怒りの感情が多いから減らそう」「もっと嬉しい気持ちを増やしたい！」といったように、日頃の感情を知ることで、自分を変えるきっかけを作ることができるのです。</p>
    <img class="col-md-6  paragraph-image" src="chart.png">
  </div>
  <div class="paragraph mb-3">
    <h2 class="col-md-6 offset-md-3"><i class="fas fa-user-slash"></i> 自己承認欲求から解放される</h2>
    <p class="col-md-6 offset-md-3">他のSNSでは、他人から評価されたい自己承認欲求の強いユーザーが数多くいます。キドアイラクでは「いいね機能」「シェア機能」「フォロー機能」を導入しないことで、必然的に承認欲求から解放される仕組みに設計しました。誰かに認められようとするのではなく、常に自分と向き合い、成長しようと前を向き続ける向上心を持ちたい方にオススメのサービスです。</p>
    <img class="col-md-6 paragraph-image" src="iinekinou.png">
  </div>
  <div class="bottom-button mb-5">
    <%= link_to "新規登録", new_user_path, class: "btn-gradient-radius" %>
      <%= link_to "ログイン", login_path, class: "btn-gradient-radius" %>
  </div>
</div>  

app/views/toppages/index.html.erb
<% if logged_in? %>
  <%= render 'posts/posts', posts: @posts %>
<% else %>
  <%= render 'toppages/before_login' %>
<% end %>