config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users do
    member do
      get :followings
      get :followers
      get :refusals
      get :refusers
      get :likes
      get :joy
      get :angry
      get :sad
      get :happy
    end
  end
  
  resources :posts, only: [:create, :destroy, :new, :show] do
    resources :comments, only: [:create, :destroy, :show, :index]
    member do
      get :joy
      get :angry
      get :sad
      get :happy
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :rejects, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :notifications, only: :index
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<div class="flash-messages" >
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">キドアイラク</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          
          <li class="nav-item mr-2 d-none d-sm-block">
            <%= link_to new_post_path(current_user), class: 'nav-link mr-2', data: {"turbolinks" => false} do %>
              <i class="fas fa-edit"></i>
            <% end %>
          </li>
          <li class="nav-item mr-2 d-none d-sm-block">
            <%= link_to user_path(current_user), class: 'nav-link mr-2' do %>
              <i class="fas fa-user"></i>
            <% end %>
          </li>
          <li class="nav-item mr-2 d-none d-sm-block">
            <%= link_to notifications_path(current_user), class: 'nav-link mr2' do %>
              <i class="fas fa-bell"></i> <span class="badge badge-light"><%= current_user.passive_notifications.where(checked: false).count %></span>
            <% end %>
          </li>
          
          <li class="nav-item mr-2 d-block d-sm-none">
            <%= link_to '投稿',  new_post_path(current_user), class: 'nav-link mr-2' %>
          </li>
          <li class="nav-item mr-2 d-block d-sm-none">
            <%= link_to 'マイページ', user_path(current_user), class: 'nav-link mr-2' %>
          </li>
          <li class="nav-item mr-2 d-block d-sm-none">
            <%= link_to notifications_path(current_user), class: 'nav-link mr2' do %>
              通知 <span class="badge badge-light"><%= current_user.passive_notifications.where(checked: false).count %></span>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>キドアイラク</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="kidoiraku.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    
    

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>